spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Hongkong&characterEncoding=utf-8&useSSL=false
    username: root
    password: fur@6289
  jpa:
    open-in-view: true
    properties:
      hibernate:
        show_sql: false
        format_sql: false
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1024,expireAfterWrite=12h
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
logging:
  file:
    path: ./logs/
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 100
    min-spare-threads: 20
  port: 8080
meta:
