spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Hongkong&characterEncoding=utf-8&useSSL=false
    username: root
    password: fur@6289
  jpa:
    open-in-view: true
    properties:
      hibernate:
        show_sql: false
        format_sql: false
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /web/**
  output:
    ansi:
      enabled: DETECT
logging:
  file:
    path: ./logs/
server:
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 100
      min-spare: 20
  port: 8088
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
meta:
